### ISSUE TITLE
Nothing exported

### ISSUE THREAD

**Issue by b3nab** [Nargonath/twitter-auth-await#1]
The folder of package (inside node_modules/) downloaded by npm is empty. 

Please upload a fixed version.

**Comment by Nargonath** [comment]
Oh that's really strange. I'll have a look into it. Thanks for reporting.

**Comment by Nargonath** [comment]
There is a problem with Travis deployment so it doesn't publish. I'll need to have a look at it later on.

**Comment by Nargonath** [comment]
Should be fixed in [1.0.1](https://github.com/Nargonath/twitter-auth-await/releases/tag/v1.0.1). Feel free to open a new issue if the problem persists but should be gone. Thanks for reporting that. The package was useless before hand. :disappointed:
