### ISSUE TITLE
Implantation question

### ISSUE THREAD

**Issue by sheksushant** [Nargonath/twitter-auth-await#2]
const { accessToken } = await _twitter_.getAccessToken(oauthToken, oauthVerifier);

in the above line of code. what is _twitter_ is not declared anywhere hence gives error.

**Comment by Nargonath** [comment]
Thanks for pointing that out. Indeed there is a mistake in the README documentation. `twitter` should be `twitterClient` that is declared in the first part of the [How it works](https://github.com/Nargonath/twitter-auth-await#how-it-works) section. I'll fix it.
